{% set name = "mattermostdriver" %}
{% set version = "7.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3b9040503d553f1188ebbaf643de61d5bcf382037f083fbfa704d31c87c3aba7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - requests >=2.19
    - websockets >=6

test:
  imports:
    - mattermostdriver
    - mattermostdriver.endpoints

about:
  home: https://github.com/Vaelor/python-mattermost-driver
  summary: A Python Mattermost Driver
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
